/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.paqutes;

import java.rmi.ConnectException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author adsi1
 */
public class paquete2 extends javax.swing.JFrame {

    private Object jTable2;
    private Object stmt;
    private Object jPanel7;

    /**
     * Creates new form paquete2
     */
    public paquete2() {
        initComponents();
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        aviso = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 700);

        jPanel5.setBackground(new java.awt.Color(0, 74, 89));
        jPanel5.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel5.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel5.setLayout(null);

        jButton6.setText("INGRESAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(170, 250, 100, 30);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CONTRASEÑA");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(190, 160, 90, 40);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("USUARIO");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(210, 90, 60, 40);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField14);
        jTextField14.setBounds(290, 90, 140, 30);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jPasswordField1);
        jPasswordField1.setBounds(290, 160, 140, 30);

        jButton9.setText("REGISTRAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(390, 250, 120, 30);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(jLabel30);
        jLabel30.setBounds(270, 210, 120, 20);

        jButton16.setText("jButton16");
        jPanel5.add(jButton16);
        jButton16.setBounds(290, 320, 79, 23);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(-9, -5, 734, 800);

        jPanel6.setBackground(new java.awt.Color(0, 74, 89));
        jPanel6.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel6.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel6.setLayout(null);
        jPanel6.add(jTextField13);
        jTextField13.setBounds(280, 60, 130, 30);
        jPanel6.add(jTextField15);
        jTextField15.setBounds(280, 100, 130, 30);
        jPanel6.add(jTextField16);
        jTextField16.setBounds(280, 140, 130, 30);

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(180, 310, 120, 40);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(380, 310, 110, 40);

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nombres");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(200, 70, 70, 17);

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Apellidos");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(200, 110, 70, 17);

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Usuario");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(210, 150, 70, 17);

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Contraseña");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(190, 190, 80, 17);

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Confirmar Contraseña");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(140, 230, 140, 17);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jPasswordField2);
        jPasswordField2.setBounds(280, 180, 130, 30);

        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jPasswordField3);
        jPasswordField3.setBounds(280, 220, 130, 30);

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Registro");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(290, 20, 90, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 700, 700);

        jPanel8.setBackground(new java.awt.Color(0, 74, 89));
        jPanel8.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel8.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel8.setLayout(null);

        jButton10.setText("ver");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10);
        jButton10.setBounds(340, 140, 80, 40);

        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Consultar");
        jPanel8.add(jLabel29);
        jLabel29.setBounds(340, 30, 100, 20);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField17);
        jTextField17.setBounds(200, 90, 340, 30);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Destinatario", "direccion", "telefono", "remitente", "talefono2", "codigo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable5);

        jPanel8.add(jScrollPane4);
        jScrollPane4.setBounds(60, 200, 640, 123);

        jButton12.setBackground(new java.awt.Color(255, 0, 0));
        jButton12.setText("SALIR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12);
        jButton12.setBounds(330, 350, 100, 40);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(10, 20, 1000, 1000);

        jPanel4.setBackground(new java.awt.Color(0, 74, 89));
        jPanel4.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel4.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destinatario", "Direccion", "Telefono_destinatario", "Remitente", "telefono_remitente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 640, 141);

        jButton5.setText("Envios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(290, 153, 100, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha_l", "Hora_l", "Fecha_s", "Hora_s", "Tamaño", "Peso", "Fragil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable3);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 240, 640, 123);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("LLEGADA");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(70, 210, 90, 17);

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SALIDA");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(260, 210, 60, 17);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("DESCRIPCION");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(440, 210, 110, 17);

        jButton7.setText("Registro");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(290, 380, 100, 30);

        jButton23.setBackground(new java.awt.Color(255, 0, 0));
        jButton23.setText("Atras");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton23);
        jButton23.setBounds(510, 480, 130, 40);

        jButton24.setBackground(new java.awt.Color(0, 255, 0));
        jButton24.setText("Editar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton24);
        jButton24.setBounds(90, 480, 140, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 700, 700);

        jPanel2.setBackground(new java.awt.Color(0, 74, 89));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de destinatario");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 60, 140, 14);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(230, 50, 262, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Direccion");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 100, 70, 17);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(230, 90, 262, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 150, 60, 17);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(230, 140, 262, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del remitente");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 210, 130, 17);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(230, 200, 262, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(150, 260, 60, 17);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(230, 250, 262, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(380, 320, 80, 40);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(480, 320, 80, 40);

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Destino");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(320, 20, 70, 21);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 700);

        jPanel3.setBackground(new java.awt.Color(0, 74, 89));
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("llegada");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(170, 30, 70, 17);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(100, 60, 70, 17);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(110, 110, 60, 17);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(170, 50, 81, 30);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(170, 100, 81, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salida");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(480, 30, 60, 17);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(470, 50, 90, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(400, 60, 60, 17);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(400, 110, 60, 17);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(470, 100, 90, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descripcion");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(300, 170, 100, 17);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tamaño");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 200, 80, 17);
        jPanel3.add(jTextField11);
        jTextField11.setBounds(290, 190, 90, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fragil");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(230, 270, 50, 17);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Peso");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(230, 230, 60, 17);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(290, 220, 90, 30);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(290, 260, 80, 30);

        jButton8.setBackground(new java.awt.Color(0, 204, 0));
        jButton8.setText("Guardar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(352, 357, 80, 40);

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setText("Cancelar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(479, 357, 90, 40);

        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Información");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(300, 10, 130, 21);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 700, 700);

        jPanel9.setBackground(new java.awt.Color(0, 74, 89));
        jPanel9.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel9.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel9.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel9.setLayout(null);

        jButton13.setText("Consultar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton13);
        jButton13.setBounds(320, 160, 100, 50);

        jButton14.setText("Destino");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton14);
        jButton14.setBounds(320, 220, 100, 50);

        jButton15.setText("Registro");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton15);
        jButton15.setBounds(320, 280, 100, 50);

        jLabel31.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("Gestion Paquetes");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(280, 80, 190, 50);

        jButton17.setBackground(new java.awt.Color(255, 0, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton17.setText("Salir");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton17);
        jButton17.setBounds(510, 430, 110, 40);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 700, 700);

        jPanel10.setBackground(new java.awt.Color(0, 74, 89));
        jPanel10.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel10.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel10.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destinatario", "Direccion", "Telefono_destinatario", "Remitente", "telefono_remitente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable4);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 640, 141);

        jButton18.setText("Envios");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton18);
        jButton18.setBounds(290, 153, 100, 30);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha_l", "Hora_l", "Fecha_s", "Hora_s", "Tamaño", "Peso", "Fragil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable6);

        jPanel10.add(jScrollPane5);
        jScrollPane5.setBounds(0, 240, 640, 123);

        jLabel32.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("LLEGADA");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(70, 210, 90, 17);

        jLabel33.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("SALIDA");
        jPanel10.add(jLabel33);
        jLabel33.setBounds(260, 210, 60, 17);

        jLabel34.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DESCRIPCION");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(440, 210, 110, 17);

        jButton19.setText("Registro");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton19);
        jButton19.setBounds(290, 380, 100, 30);

        jButton20.setBackground(new java.awt.Color(255, 0, 0));
        jButton20.setText("Salir");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton20);
        jButton20.setBounds(510, 480, 130, 40);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 0, 700, 700);

        jPanel11.setBackground(new java.awt.Color(0, 74, 89));
        jPanel11.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel11.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel11.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nombre de destinatario");
        jPanel11.add(jLabel35);
        jLabel35.setBounds(60, 60, 140, 17);
        jPanel11.add(jTextField18);
        jTextField18.setBounds(230, 50, 262, 30);

        jLabel36.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Direccion");
        jPanel11.add(jLabel36);
        jLabel36.setBounds(150, 100, 70, 17);
        jPanel11.add(jTextField19);
        jTextField19.setBounds(230, 90, 262, 30);

        jLabel37.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Telefono");
        jPanel11.add(jLabel37);
        jLabel37.setBounds(150, 150, 60, 17);
        jPanel11.add(jTextField20);
        jTextField20.setBounds(230, 140, 262, 30);

        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Nombre del remitente");
        jPanel11.add(jLabel38);
        jLabel38.setBounds(80, 210, 130, 14);
        jPanel11.add(jTextField21);
        jTextField21.setBounds(230, 200, 262, 30);

        jLabel39.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Telefono");
        jPanel11.add(jLabel39);
        jLabel39.setBounds(150, 260, 60, 17);
        jPanel11.add(jTextField22);
        jTextField22.setBounds(230, 250, 262, 30);

        jButton21.setBackground(new java.awt.Color(255, 0, 0));
        jButton21.setText("Atras");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton21);
        jButton21.setBounds(180, 330, 80, 40);

        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Destino");
        jPanel11.add(jLabel40);
        jLabel40.setBounds(320, 20, 70, 21);
        jPanel11.add(aviso);
        aviso.setBounds(370, 350, 0, 0);

        jButton22.setBackground(new java.awt.Color(0, 204, 0));
        jButton22.setText("Actualizar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton22);
        jButton22.setBounds(440, 330, 80, 40);

        getContentPane().add(jPanel11);
        jPanel11.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(true);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            String ins = "INSERT INTO envios VALUES('" + jTextField2.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "','" + jTextField5.getText() + "','" + jTextField6.getText() + "');";
            System.out.println(ins);
            int r = stmt.executeUpdate(ins);
            stmt.close();
            cn.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel6.setVisible(false);
            jPanel8.setVisible(false);
            jPanel9.setVisible(true);
            jPanel5.setVisible(false);
            jPanel10.setVisible(false);
            jPanel11.setVisible(false);
            
        } catch (SQLException sqle) {
       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            String usuario = jTextField14.getText();
             char[] contr = jPasswordField1.getPassword();
            String cont = new String(contr);
            String oe=null;
            try{
            Statement stmt = ci.createStatement();
            ResultSet ls = stmt.executeQuery("SELECT *FROM ROLES");  
            while (ls.next()) {
                if (cont.equals(ls.getString(3)) && usuario.equals(ls.getString(2))) {
                    oe = ls.getString(1);
                    System.out.println("las contraseñas coinciden");
                    System.out.println(oe);
                    if (oe.equals("gerente")) {
                        System.out.println("El rol es correcto");
                        jPanel4.setVisible(false);
                        jPanel1.setVisible(false);
                        jPanel2.setVisible(false);
                        jPanel3.setVisible(false);
                        jPanel5.setVisible(false);
                        jPanel6.setVisible(false);
                        jPanel8.setVisible(false);
                        jPanel9.setVisible(false);
                        jPanel10.setVisible(true);
                        jPanel11.setVisible(false);
                    }  if (oe.equals("secretario")) {
                         System.out.println("El rol es correcto");
                        jPanel9.setVisible(true);
                        jPanel4.setVisible(false);
                        jPanel1.setVisible(false);
                        jPanel2.setVisible(false);
                        jPanel3.setVisible(false);
                        jPanel5.setVisible(false);
                        jPanel6.setVisible(false);
                        jPanel8.setVisible(false);
                        jPanel10.setVisible(false);
                        jPanel11.setVisible(false);

                    } if (oe.equals("cliente")) {
                        jPanel4.setVisible(false);
                        jPanel1.setVisible(false);
                        jPanel2.setVisible(false);
                        jPanel3.setVisible(false);
                        jPanel5.setVisible(false);
                        jPanel6.setVisible(false);
                        jPanel8.setVisible(true);
                        jPanel9.setVisible(false);
                        jPanel10.setVisible(false);
                        jPanel11.setVisible(false);
                    }
                }
            
            }
            ls.close();
            stmt.close();
            ls.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            
            } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            Statement stmt = ci.createStatement();
            String ina = "INSERT INTO Ingreso VALUES('" + jTextField14.getText() + "','" + jPasswordField1.getPassword() + "');";
            System.out.println(ina);
            int r = stmt.executeUpdate(ina);
            stmt.close();

            ci.close();

        } catch (SQLException sqle) {

        }
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            Statement stmt = ci.createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("select *from envios");

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);

                tableModel.addRow(filas);
            }

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            Statement stmt = ci.createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("select *from REGISTRO");

            DefaultTableModel tableModel = (DefaultTableModel) jTable3.getModel();
            Object[] filas = new Object[jTable3.getColumnCount()];
            for (int i = jTable3.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable3.getModel()).removeRow(i);
            }
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);
                filas[5] = rs.getString(6);
                filas[6] = rs.getString(7);

                tableModel.addRow(filas);
            }

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Calendar MiCalendario = Calendar.getInstance();
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(true);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        jTextField13.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection cu = sqlite.Conectar();
            Statement stmt = cu.createStatement();
            String inq = "INSERT INTO REGISTRO VALUES('" + jTextField7.getText() + "','" + jTextField8.getText() + "','" + jTextField9.getText() + "','" + jTextField10.getText() + "','" + jTextField11.getText() + "','" + jTextField12.getText() + "','" + jTextField1.getText() + "');";
            System.out.println(inq);
            int r = stmt.executeUpdate(inq);
            stmt.close();

            cu.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel6.setVisible(false);
            jPanel8.setVisible(false);
            jPanel9.setVisible(true);
            jPanel5.setVisible(false);
            jPanel10.setVisible(false);
            jPanel11.setVisible(false);
        } catch (SQLException sqle) {

        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(true);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection cq = sqlite.Conectar();
            Statement stmt = cq.createStatement();
            String ink = "INSERT INTO registrar VALUES('" + jTextField13.getText() + "','" + jTextField15.getText() + "','" + jTextField16.getText() + "','" + jPasswordField2.getPassword() + "','" + jPasswordField3.getPassword() + "');";
            System.out.println(ink);
            int r = stmt.executeUpdate(ink);
            stmt.close();

            cq.close();

        } catch (SQLException sqle) {

        }
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection cq = sqlite.Conectar();
            Statement stmt = cq.createStatement();
            char[] ps = jPasswordField2.getPassword();
            String clave = new String(ps);
            String ink = "INSERT INTO ROLES VALUES('cliente','" + jTextField16.getText() + "','" + clave + "');";
            System.out.println(ink);
            int r = stmt.executeUpdate(ink);
            stmt.close();

            cq.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

        } catch (SQLException sqle) {

        }
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            Statement stmt = ci.createStatement();

            ResultSet rs;

            String rec;
            rec = "select *from envios where remitente='" + jTextField17.getText() + "';";
            System.out.println(rec);

            rs = stmt.executeQuery(rec);

            DefaultTableModel tableModel = (DefaultTableModel) jTable5.getModel();
            Object[] filas = new Object[jTable5.getColumnCount()];
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);

                tableModel.addRow(filas);
            }
            ci.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        } catch (SQLException ed) {
            JOptionPane.showMessageDialog(null, "error");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Calendar MiCalendario = Calendar.getInstance();
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        jTextField14.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        jTextField14.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            Statement stmt = ci.createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("select *from envios");

            DefaultTableModel tableModel = (DefaultTableModel) jTable4.getModel();
            Object[] filas = new Object[jTable4.getColumnCount()];

            for (int i = jTable4.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable4.getModel()).removeRow(i);
            }
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);

                tableModel.addRow(filas);
            }

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            GestionDePaqutes sqlite = new GestionDePaqutes();
            Connection ci = sqlite.Conectar();
            Statement stmt = ci.createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("select *from REGISTRO");

            DefaultTableModel tableModel = (DefaultTableModel) jTable6.getModel();
            Object[] filas = new Object[jTable6.getColumnCount()];
            for (int i = jTable6.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable6.getModel()).removeRow(i);
            }
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);
                filas[5] = rs.getString(6);
                filas[6] = rs.getString(7);

                tableModel.addRow(filas);
            }

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        jTextField14.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);  
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
         jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(true);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paquete2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paquete2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paquete2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paquete2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paquete2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
